### ISSUE TITLE
## Bilal's Task:Week 1 - 21-27 Feb

### ISSUE THREAD

**Issue by alpsencer** [campusmatcher/learning#4]
We will follow this course https://www.udemy.com/course/complete-android-course/
Our first week goals are listed below:
- [ ] Chapter 3: Getting Started
  - [x]  Introduction & Setup
  - [x]  Android Studio
  - [x]  Android Lifecycle
  - [x]  Android Emulator
  - [x]  Running app on a Real Android device (if it is available)
  - [x]  Android Layouts
  - [x]  Android Countdown app ( **OUR MAIN GOAL IS FINISHING THIS APP** )
  - [x]  Application Themes & Basic Color Preferences

**Comment by abilalkar** [comment]
I have finished the following parts: Introduction & Setup, Android Studio, Android Lifecycle, Android Emulator, Running app on a Real Android Device and Android Layouts.

**Comment by abilalkar** [comment]
I have watched all and created a working APK file of countdown timer.
